spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/labchelin
    driver-class-name: org.mariadb.jdbc.Driver
    username: lab
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect